### ISSUE TITLE
Windows10 Python3.8.0 使用 create_contest.py 失败

### ISSUE THREAD

**Issue by JJLeo** [buaaacm/DOMjudge_Contest#3]
![~` 1H7~T)QZ V}WXL8$D)E9](https://user-images.githubusercontent.com/17369759/138486699-59023df1-8bd5-4394-bd44-2d539fea2ae4.png)

中间多行乱码

![D E%LR95KMQ`RXB@M40HT92](https://user-images.githubusercontent.com/17369759/138486834-d117ccf5-3f14-4c5e-9046-33a2f986d37b.png)

**Comment by zzzzzzh** [comment]
目前代码需要使用 `unix2dos`，不太方便在 Windows 上使用，所以这个问题就暂时搁置了。
